name: 'Terraform'

on:
  push:
    branches:
    - main

jobs:
  terraform:
  name: 'Terraform'
  runs-on: ubuntu-latest
  environment: production
  defaults: 
    run: 
      shell:bash
      working-directory: ./main
  env:
    ARM_CLIENT_ID:
    ARM_CLIENT_SECRET:
    ARM_SUBSCRIPTION_ID:
    ARM_TENANT_ID:
    TF_VERSION: 1.6.6


  steps:
  # Checkout the preository to the GitHub Actions runner
  - name: Checkout
    uses: actions/checkout@v4.1.1

    
