name: 'Terraform'

on:
  push:
    branches:
    - main

jobs:
  terraform:
  name: 'Terraform'
  env:
  ARM_CLIENT_ID:
  ARM_CLIENT_SECRET:
  ARM_SUBSCRIPTION_ID:
  ARM_TENANT_ID:
  TF_VERSION: 1.6.6
runs-on: ubuntu-latest
environment: production

  steps:
  # Checkout the preository to the GitHub Actions runner
  - name: Checkout
    uses: actions/checkout@v4.1.1

    
